FROM node:17.9-alpine3.15 AS BUILDER
WORKDIR /workspace
COPY package.json yarn.lock* ./
RUN yarn install

FROM node:17.9-alpine3.15
WORKDIR /workspace
COPY --from=BUILDER --chown=node:node /workspace/node_modules ./node_modules
USER node
COPY --chown=node:node . .
CMD [ "yarn","dev" ]